# Generated by Django 5.2.6 on 2025-09-27 14:59

from django.db import migrations


def seed_libros(apps, schema_editor):
    Libro = apps.get_model('libreria', 'Libro')
    
    libros_data = [
        {
            'titulo': 'Don Quijote de la Mancha',
            'autor': 'Miguel de Cervantes',
            'precio': 15990.00,
            'descripcion': 'La obra cumbre de la literatura española que narra las aventuras de un hidalgo que enloquece leyendo libros de caballerías.',
            'disponible': True
        },
        {
            'titulo': 'Cien años de soledad',
            'autor': 'Gabriel García Márquez',
            'precio': 18500.00,
            'descripcion': 'La historia épica de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo.',
            'disponible': True
        },
        {
            'titulo': 'La casa de los espíritus',
            'autor': 'Isabel Allende',
            'precio': 16750.00,
            'descripcion': 'Una saga familiar que abarca cuatro generaciones de mujeres fuertes en el Chile del siglo XX.',
            'disponible': True
        },
        {
            'titulo': 'Rayuela',
            'autor': 'Julio Cortázar',
            'precio': 14250.00,
            'descripcion': 'Una novela experimental que puede leerse de múltiples maneras, explorando el amor y la búsqueda del sentido.',
            'disponible': True
        },
        {
            'titulo': 'El amor en los tiempos del cólera',
            'autor': 'Gabriel García Márquez',
            'precio': 17000.00,
            'descripcion': 'Una historia de amor que dura más de cincuenta años, desde la juventud hasta la vejez de sus protagonistas.',
            'disponible': True
        },
        {
            'titulo': 'La sombra del viento',
            'autor': 'Carlos Ruiz Zafón',
            'precio': 19990.00,
            'descripcion': 'Una novela de misterio ambientada en la Barcelona de posguerra, donde un joven descubre un libro maldito.',
            'disponible': True
        },
        {
            'titulo': 'Como agua para chocolate',
            'autor': 'Laura Esquivel',
            'precio': 13500.00,
            'descripcion': 'Una historia mágica donde las emociones se transmiten a través de la cocina y los alimentos.',
            'disponible': True
        },
        {
            'titulo': 'Pedro Páramo',
            'autor': 'Juan Rulfo',
            'precio': 12990.00,
            'descripcion': 'Una obra maestra del realismo mágico que narra la búsqueda de un padre en un pueblo fantasma.',
            'disponible': True
        },
        {
            'titulo': 'El Aleph',
            'autor': 'Jorge Luis Borges',
            'precio': 15500.00,
            'descripcion': 'Una colección de cuentos que exploran temas universales como el tiempo, el infinito y la realidad.',
            'disponible': True
        }
    ]
    
    for libro_data in libros_data:
        Libro.objects.create(**libro_data)


def reverse_seed_libros(apps, schema_editor):
    Libro = apps.get_model('libreria', 'Libro')
    Libro.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_libro_descripcion_libro_portada'),
    ]

    operations = [
        migrations.RunPython(seed_libros, reverse_seed_libros),
    ]
