# Generated by Django 5.2.5 on 2025-09-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_libro_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='edad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
